---
- name: Create LUN
  netapp.ontap.na_ontap_restit:
    hostname: '{{ ontap_host }}'
    cert_filepath: '{{ ontap_crt }}'
    key_filepath: '{{ ontap_key }}'
    http_port: '{{ ontap_port }}'
    use_rest: always
    validate_certs: false
    api: storage/luns
    method: POST
    body:
      name: '{{ ontap_lun_path }}'
      comment: "{{ ontap_comment if ontap_comment is defined else 'Provisioned by Ansible'}}"
      svm: '{{ ontap_vserver }}'
      space:
        size: '{{ ontap_size }}'
      os_type: linux
  register: lun_create_info

- debug: var=lun_create_info
- assert: { that: lun_create_info.status_code==201 }
