---
- name: Get LUNs
  netapp.ontap.na_ontap_restit:
    hostname: '{{ ontap_host }}'
    cert_filepath: '{{ ontap_crt }}'
    key_filepath: '{{ ontap_key }}'
    http_port: '{{ ontap_port }}'
    use_rest: always
    validate_certs: false
    wait_for_completion: true
    api: storage/luns
    query:
      fields: comment
  register: lun_info
- debug: var=lun_info
- assert: { that: lun_info.status_code==200 }

- name: Store LUN dump
  local_action:
    module: copy
    content: '{{ lun_info }}'
    dest: /dev/shm/luns.out

# I'm sure there's a native way to do this...
- name: Get highest LUN
  ansible.builtin.shell:
    cmd: "grep -Po 'lun\\K(\\d+)' /dev/shm/luns.out | sort -nu | tail -n1"
  register: lun_grep

- name: Define LUN number
  set_fact:
    lun_id: '{{ lun_grep.stdout | int + 1 }}'

- name: Dump gathered variables
  ansible.builtin.debug:
    msg: 'LUN ID defined as {{ lun_id }}'
