---
- name: Patch LUN
  netapp.ontap.na_ontap_restit:
    hostname: '{{ ontap_host }}'
    cert_filepath: '{{ ontap_crt }}'
    key_filepath: '{{ ontap_key }}'
    http_port: '{{ ontap_port }}'
    use_rest: always
    validate_certs: false
    api: storage/luns
    method: PATCH
    query:
      name: '{{ ontap_lun_path }}'
    body:
      space:
        size: '{{ ontap_size }}'
  register: lun_patch_info

- debug: var=lun_patch_info
- assert: { that: lun_patch_info.status_code==200 }

- local_action:
    module: copy
    content: '{{ lun_patch_info }}'
    dest: /tmp/lun_patch.out
