---
- hosts: localhost
  name: Delete LUN
  connection: local
  gather_facts: False

  tasks:
    - name: Delete
      block:
        - name: Delete LUN
          import_tasks: "{{ '../tasks/delete_lun_restit.yml' if ontap_lun_uuid is defined else '../tasks/delete_lun_restit_by_path.yml' }}"
